In [1]:
import pandas as pd
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [3]:
df = pd.read_csv('2010YumaAZ.csv')
days=['TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY','MONDAY']

In [4]:
df.head()

   LST_DATE      DAY LST_TIME  T_HR_AVG
0  20100601  TUESDAY     0:00      25.2
1  20100601  TUESDAY     1:00      24.1
2  20100601  TUESDAY     2:00      24.4
3  20100601  TUESDAY     3:00      24.9
4  20100601  TUESDAY     4:00      22.8

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LST_DATE  168 non-null    int64
 1   DAY       168 non-null    object
 2   LST_TIME  168 non-null    object
 3   T_HR_AVG  168 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 5.4+ KB

In [6]:
df['LST_TIME']

0       0:00
1       1:00
2       2:00
3       3:00
4       4:00
       ...
163    19:00
164    20:00
165    21:00
166    22:00
167    23:00
Name: LST_TIME, Length: 168, dtype: object

In [9]:
data = []

for day in days:
    trace =go.Scatter(x=df['LST_TIME'] ,y=df[df['DAY']==day]['T_HR_AVG'],mode='lines',name=day)
    data.append(trace)
    
#data = [go.scatter(x=df['LST_TIME'],y=df[df['DAY']==day]['T_HR_AVG'],mode='lines',name=day) for day in df['DAY'].unique()]

In [10]:
data

[Scatter({
     'mode': 'lines',
     'name': 'TUESDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([25.2, 24.1, 24.4, 24.9, 22.8, 19.8, 18.8, 21.2, 24.2, 27.1, 29.3, 30.6,
                 32.6, 34. , 34. , 34.9, 34.6, 33.8, 33.5, 32.8, 31. , 29. , 27.6, 26.3])
 }), Scatter({
     'mode': 'lines',
     'name': 'WEDNESDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([23.8, 20.6, 19.1, 18.4, 18.9, 18.2, 17.9, 20.2, 23.8, 26.1, 27.9, 29.3,
                 30.9, 32.2, 33.1, 33.7, 34.5, 34.7, 34.8, 34.2, 32.8, 31. , 28.7, 25.5])
 }), Scatter({
     'mode': 'lines',
     'name': 'THURSDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([24.3, 23.1, 21.8, 19.8, 18.5, 19.2, 19.7, 20.7, 23.2, 26.1, 28.6, 30.8,
                 32.3, 33.8, 34.9, 35.8, 35.9, 36.3, 35.8, 35.4, 34.2, 32.7, 31.1, 28.6])
 }), Scatter({
     'mode': 'lines',
     'name': 'FRIDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([26.4, 25.4, 24.2, 23.6, 22.5, 21. , 21.3, 22.5, 24.7, 28.1, 30.6, 32.5,
                 33.9, 35.5, 36.6, 37.2, 37.8, 38.1, 38.2, 37.4, 36. , 34.4, 32.6, 30.1])
 }), Scatter({
     'mode': 'lines',
     'name': 'SATURDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([28.3, 27.3, 26.3, 25.3, 24.7, 24.7, 23.9, 24.7, 27.7, 30.4, 32.6, 34.8,
                 36.4, 37.2, 38.4, 39.7, 40. , 40.4, 40.1, 39. , 37.3, 35.7, 33.9, 31.4])
 }), Scatter({
     'mode': 'lines',
     'name': 'SUNDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([29.7, 28.6, 26.9, 25.9, 25.2, 24.8, 23.9, 26.1, 27.9, 30.5, 33.7, 35.6,
                 36.9, 38.4, 39.2, 40.2, 40.6, 40.6, 40.3, 39.5, 37.9, 36.5, 35. , 32.9])
 }), Scatter({
     'mode': 'lines',
     'name': 'MONDAY',
     'x': array(['0:00', '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00',
                 '9:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
                 '17:00', '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00',
                 '1:00', '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00',
                 '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00',
                 '18:00', '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00',
                 '2:00', '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00', '0:00', '1:00', '2:00',
                 '3:00', '4:00', '5:00', '6:00', '7:00', '8:00', '9:00', '10:00',
                 '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
                 '19:00', '20:00', '21:00', '22:00', '23:00'], dtype=object),
     'y': array([30.9, 28.7, 26.9, 25.2, 24.1, 24.3, 23.4, 25.7, 28.5, 30.7, 32.5, 34.1,
                 36.1, 37.6, 39. , 40.2, 40.3, 40.2, 40.1, 39.4, 38.5, 37. , 34.7, 32.6])
 })]

In [13]:
layout = go.Layout(title='Daily temp avgs')
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='TempAvgs.html')

'TempAvgs.html'